### ISSUE TITLE
QAQC: 06-10 

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-factfinder#178] opened 2021-07-22 16:53 UTC
# Discrepancies by percent difference

- More than 10% difference, defined as ((code value - sample value)/(sample value)) * 100: 
    - Tract-level: [pct_diff_o10_2010.csv.zip](https://github.com/NYCPlanning/db-factfinder/files/6955552/pct_diff_o10_2010.csv.zip)
    - Above tract: [pct_diff_o10_2010_nontract.csv.zip](https://github.com/NYCPlanning/db-factfinder/files/6955657/pct_diff_o10_2010_nontract.csv.zip)
- Between 1% and 10% difference: 
    - Tract-level: [pct_diff_1t10_2010.csv.zip](https://github.com/NYCPlanning/db-factfinder/files/6955560/pct_diff_1t10_2010.csv.zip)
    - Above tract: [pct_diff_1t10_2010_nontract.csv.zip](https://github.com/NYCPlanning/db-factfinder/files/6955663/pct_diff_1t10_2010_nontract.csv.zip)

- Differences in NULLS: 
    - Tract-level: [null_diffs_2010.csv.zip](https://github.com/NYCPlanning/db-factfinder/files/6955718/null_diffs_2010.csv.zip)
    - Above tract: [null_diff_2010_nontract.csv.zip](https://github.com/NYCPlanning/db-factfinder/files/6955782/null_diff_2010_nontract.csv.zip)

 

# As of rewriting median as a class #188 

## Estimate differences
- [ ] 36061000600 mdvl
- [ ] 36005020100 mdvl
- [x] 36005043501 mdhhinc > based on comment, we are right

## MOE differences
- [ ] 36047028501 mdefftwrk
- [ ] 36061011900 mdfaminc
- [ ] 36081003700 mdhhinc
- [ ] 36081017800 mdnfinc
- [ ] popu18_2 for several tracts: 36081064102, 36047017500, 36061010200, 36047001100, 36005031900, 36081056100, etc.
- [x] mntrvtm for several tracts: 36047005302, 36005031900, 36081042600, 36081001903, 36005001901, 36081001902, etc.#199

# As of [this run](https://github.com/NYCPlanning/db-factfinder/actions/runs/1078895231)

- [x] Tract mismatch

## Metadata
- [x] Check on metadata for popu18_2, popu18m, popu18f -- e, m, p, z discrepancies across tracts
- [x] Large m differences for fpop20t24 (example tracts: 36005009600, 36005013000, 36047019200, 36081052100)
- [x] fam1 is missing from metadata, but is necessary for popinfms, fam3, avgfmsz at the CT20, CDTA, NTA level
- [x] Large discrepancies in oeeur for e, m, p, and z for 345 tracts (example tracts: 36005025000, 36047054200, 36081006100, 36081058100, 36085018703, 36085018704) 

## Estimate differences
- [x] Large estimate discrepancies for percapinc, agttm, aghhinc, agip15pl, mnhhinc

## MOE differences
- [x] Some large m differences for mdvl and mdgr (might be related to outstanding methodology issues, not specific to 2010 data). Example tracts: 36005017902, 36005005002, 36047035900, 36005001902, 36081140902, 36081100801, 36047068000 (#188)
- [ ] Some large m differences for popu18_2. Example tracts: 36081064102, 36081064102, 36061010200, 36047017500
- [x] Large m difference for mntrvtm for tract 36047044902.
- [x] For several tracts, non-zero vacrnt e matches but sample m is 0, while pff m non-zero. Tract 36005039300 is an example. Based on data in 2010 geographies, it looks like inputs do not match.
- [x] For several tracts, e matches but sample m is smaller than pff m for: rntvacu, rshp_ssup
- [x] A few tracts have significantly smaller sample m than pff m: ea_lthsgr, ea_bchdh, ~~rshp_ssup, mntrvtm~~

**Comment by EricaMaurer** [comment] 2021-07-23 20:31
-- Check on metadata for popu18_2, popu18m, popu18f -- e, m, p, z discrepancies across tracts... _fixed in metadata_
-- Large m differences for fpop20t24 -- _check metadata... not sure what the issue is. looks ok in metadata_
-- Large discrepancies in oeeur for e, m, p, and z -- check on metadata... _not sure what the issue is. looks ok in metadata_
--  Large estimate discrepancies for percapinc, agttm, aghhinc, agip15pl, mnhhinc... _fixed agttm, agip15pl, and aghhinc. this should hopefully fix percapinc and mnhhinc._
-- Some large m differences for mdvl and mdgr (might be related to outstanding methodology issues, not specific to 2010 data)_... will look into this_
-- For several tracts, non-zero vacrnt e matches but sample m is 0, while pff m non-zero. Tract 36005039300 is an example_... fixed._
--  For several tracts, e matches but sample m is smaller than pff m for: rntvacu, rshp_ssup_... fixed rshp_ssup. not seeing anything off the bat for rntvacu, will look into this more_
--  A few tracts have significantly smaller sample m than pff m: ea_lthsgr, ea_bchdh, rshp_ssup, mntrvtm_... fixed rshp_ssup. mntrvtm should hopefully be fixed with the agttm fix above. not seeing anything for ea_lthsgr or ea_bchdh off the bat, will look into this more_

**Comment by EricaMaurer** [comment] 2021-07-27 14:50
fpop20t24 -- fixed
oeeur -- fixed metadata
mdvl and mdgr -- check that bins are updated.
-- mdvl ends with OV1milpl. Ov1t149m, Ov150t199m, and Ov2milpl are not used
-- mdgr ends with r2000pl. r2kt2499, r2p5t2999, r3kt3499, and r3500pl are not used
ea_lthsgr, ea_bchdh -- fixed

**Comment by mgraber** [comment] 2021-07-27 16:23
@EricaMaurer what are the bounds for the missing median inputs? Wouldn't Ov1t149m and Ov150t199m overlap if they mean 1 thousand to 149 million, and 150 thousand to 199 million?

**Comment by EricaMaurer** [comment] 2021-08-03 13:27
Estimate:
-mdvl (36061000600): median value is 48, falls in first bin (with 51 units). median = 9,313
-mdvl (36005020100): median value is 10, falls in first bin (with 11 units). median = 9,090
-mdhhinc (36005043501): calculator was bottom-coding the median. okay to calculate it. median would be 15,207 and MOE would be 17,962

MOE:
- mdefftwrk (36047028501): 
-- lower bound C1 = 0 (bin 12)
-- lower bound C2 = 100 (bin 13)
-- lower bound A1 = 0 (C1 = 0)
-- lower bound A2 = 2,499.9999 (C1 = 0, pull from first bin)
-- lower bound = 17.7795048403726
-- upper bound C1 = 0 (bin 12)
-- upper bound C2 = 100 (bin 13)
-- upper bound A1 = 35,000 (bin 12)
-- upper bound A2 = 39,999.999 (bin 13)
-- upper bound = 39964.4408896081
-- MOE = 32856.1289889714

- mdfaminc (36061011900):
-- lower bound C1 = 0 (bin 5)
-- lower bound C2 = 100 (bin 6)
-- lower bound A1 = 0 (C1 = 0)
-- lower bound A2 = 9,999.9999 (C1 = 0, pull from first bin)
-- lower bound = 1054.21788338919
-- upper bound C1 = 0 (bin 5)
-- upper bound C2 = 100 (bin 6)
-- upper bound A1 = 30,000 (bin 5)
-- upper bound A2 = 34,999.9999 (bin 6)
-- upper bound = 34472.8909635765
-- MOE = 27486.8586084541

- mdhhinc (36081003700): median is bottom-coded so MOE is blank

-  mdnfinc (36081017800):
-- lower bound C1 = 0 (bin 2)
-- lower bound C2 = 89.5 (bin 3)
-- lower bound A1 = 0 (C1 = 0)
-- lower bound A2 = 9,999.9999 (C1 = 0, pull from first bin)
-- lower bound = 2083.52920052093
-- upper bound C1 = 0 (bin 2)
-- upper bound C2 = 89.5 (bin 3)
-- upper bound A1 = 15,000 (bin 2)
-- upper bound A2 = 19,999.9999 (bin 3)
-- upper bound = 19546.4705925101
-- MOE = 14363.2692949111

- popu18_2: fixed

- mntrvtm: may have to dig into this more if it's a problem in both files
- 36047005302
-- agttmE: 522.701271186441
-- agttmM: 922.659070633512
-- wrkrnothmE: 11.8246822033898
-- wrkrnothmM: 22.3386143465341
-- MOE = 114.289455595828

**Comment by SPTKL** [comment] 2021-08-10 14:42
- the only significant remaining issues
36047070202	mdrms	4.8	4.8	0	4.3	3.9	0.10256410256410255						
36061011900	mdrms	1	1.2	0.16666666666666663	1.2	0.2	5						
36081003700	mdrms	4	4	0	1.2	0.8	0.4999999999999999						
36081038302	mdrms	5.5	9	0.3888888888888889									
36085022801	mdrms	6.1	6.1	0	0.8	0.5	0.6000000000000001						
BK56	mdrms	4.8	4.8	0	4.3	3.9	0.10256410256410255						
BK5691	mdrms	4.8	4.8	0	4.3	3.9	0.10256410256410255						
QN81	mdrms	5.5	9	0.3888888888888889									
QN8191	mdrms	5.5	9	0.3888888888888889									
QN84	mdrms	7.4	9	0.17777777777777773									
SI0391	mdrms	6.1	6.1	0	0.8	0.5	0.6000000000000001						
QN1001	mdage	35	35	0	0.8	0.9	0.11111111111111108

**Comment by SPTKL** [comment] 2021-08-12 17:26
#201

**Closed** 2021-08-19 14:30 UTC
Labels: QAQC
